pluginManagement { repositories { gradlePluginPortal(); maven { url = 'https://maven.neoforged.net/releases' } } }
dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS); repositories { maven { url = 'https://maven.neoforged.net/releases' } } }
rootProject.name = 'SpaceOre'
